version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    image: wendysanarwanto/dockerapp
    # volumes:
    #   - ./app:/app

  redis:
    extends:
      file: common.yml
      service: redis
